### ISSUE TITLE
EnergyPlus 8-5-0 opens as 8-3-0 on OS X

### ISSUE THREAD

**Issue by rustymyers** [NREL/EnergyPlusBuildSupport#30] opened 2016-07-11 18:14 UTC
Latest release download for EnergyPlus 8-5-0 launches as 8-3-0 and fails to find weather data
Steps to reproduce:

1. Download latest release to MacOS 10.11.5
2. Install using Package
3. Launch /Applicatinos/EnergyPlus-8-5-0/EP-Launch Lite.app
4. Error message appears "AppleScript Error File Macintosh HD:Applications:EnergyPlus-8-3-0:WeatherData wasn’t found. (-43)"

Appears to be old paths in /bin/Mac/EP-Launch_Lite/Application.applescript BuildSupport files.

**Comment by mjwitte** [comment] 2016-07-11 18:42
This is a duplicate of #5414, so I will close this one.  @JasonGlazer If there is a workaround for this, please add that to #5414.

**Closed by mjwitte** 2016-07-11 18:42 UTC

**Comment by JasonGlazer** [comment] 2016-07-11 19:07
@mjwitte I think you mean #[5415](https://github.com/NREL/EnergyPlus/issues/5415)

No workaround.
